[build]
  publish = "public"
  command = "hugo -D"

[context.production.environment]
  HUGO_VERSION = "0.71.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.71.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.71.0"
  HUGO_ENABLEGITINFO = "true"
